-- Generated by Oracle SQL Developer Data Modeler 24.3.1.351.0831
--   at:        2025-10-29 13:37:27 MSK
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE Album 
    ( 
     album_id     INTEGER  NOT NULL , 
     album_title  VARCHAR (100)  NOT NULL , 
     release_year DATE  NOT NULL 
    ) 
;

ALTER TABLE Album 
    ADD CONSTRAINT Album_PK PRIMARY KEY ( album_id ) ;

CREATE TABLE Artist 
    ( 
     artist_id   INTEGER  NOT NULL , 
     artist_name VARCHAR (100)  NOT NULL , 
     country     VARCHAR (50)  NOT NULL 
    ) 
;

ALTER TABLE Artist 
    ADD CONSTRAINT Artist_PK PRIMARY KEY ( artist_id ) ;

CREATE TABLE Playlist 
    ( 
     playslist_id  INTEGER  NOT NULL , 
     playlist_name VARCHAR (100)  NOT NULL , 
     User1_user_id INTEGER  NOT NULL 
    ) 
;

ALTER TABLE Playlist 
    ADD CONSTRAINT Playlist_PK PRIMARY KEY ( playslist_id ) ;

CREATE TABLE Relation_8 
    ( 
     Artist_artist_id INTEGER  NOT NULL , 
     Track_track_id   INTEGER  NOT NULL 
    ) 
;

ALTER TABLE Relation_8 
    ADD CONSTRAINT Relation_8_PK PRIMARY KEY ( Artist_artist_id, Track_track_id ) ;

CREATE TABLE Relation_9 
    ( 
     Track_track_id        INTEGER  NOT NULL , 
     Playlist_playslist_id INTEGER  NOT NULL 
    ) 
;

ALTER TABLE Relation_9 
    ADD CONSTRAINT Relation_9_PK PRIMARY KEY ( Track_track_id, Playlist_playslist_id ) ;

CREATE TABLE Track 
    ( 
     track_id       INTEGER  NOT NULL , 
     track_title    VARCHAR (100)  NOT NULL , 
     duration       DATE  NOT NULL , 
     Album_album_id INTEGER  NOT NULL 
    ) 
;

ALTER TABLE Track 
    ADD CONSTRAINT Track_PK PRIMARY KEY ( track_id ) ;

CREATE TABLE User1 
    ( 
     user_id  INTEGER  NOT NULL , 
     username VARCHAR (100)  NOT NULL , 
     email    VARCHAR (100)  NOT NULL 
    ) 
;

ALTER TABLE User1 
    ADD CONSTRAINT User1_PK PRIMARY KEY ( user_id ) ;

ALTER TABLE Playlist 
    ADD CONSTRAINT Playlist_User1_FK FOREIGN KEY 
    ( 
     User1_user_id
    ) 
    REFERENCES User1 
    ( 
     user_id
    ) 
;

ALTER TABLE Relation_8 
    ADD CONSTRAINT Relation_8_Artist_FK FOREIGN KEY 
    ( 
     Artist_artist_id
    ) 
    REFERENCES Artist 
    ( 
     artist_id
    ) 
;

ALTER TABLE Relation_8 
    ADD CONSTRAINT Relation_8_Track_FK FOREIGN KEY 
    ( 
     Track_track_id
    ) 
    REFERENCES Track 
    ( 
     track_id
    ) 
;

ALTER TABLE Relation_9 
    ADD CONSTRAINT Relation_9_Playlist_FK FOREIGN KEY 
    ( 
     Playlist_playslist_id
    ) 
    REFERENCES Playlist 
    ( 
     playslist_id
    ) 
;

ALTER TABLE Relation_9 
    ADD CONSTRAINT Relation_9_Track_FK FOREIGN KEY 
    ( 
     Track_track_id
    ) 
    REFERENCES Track 
    ( 
     track_id
    ) 
;

ALTER TABLE Track 
    ADD CONSTRAINT Track_Album_FK FOREIGN KEY 
    ( 
     Album_album_id
    ) 
    REFERENCES Album 
    ( 
     album_id
    ) 
;



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             7
-- CREATE INDEX                             0
-- ALTER TABLE                             13
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
